### ISSUE TITLE
Add in ranked position to ranked stats.

### ISSUE THREAD

**Issue by EthanHicks1** [DevilXD/HiRezAPI#4]
Currently under the `arez.RankedStats` class there doesn't seem to be any way to access a person's `position` in their rank stats. 

It would nice to see something like `.position` added to access this information.

**Comment by DevilXD** [comment]
Is this a field that's provided by the API? If so, do you happen to know which one?

**Comment by EthanHicks1** [comment]
I believe it should just be under the field `Rank`.  Should be in a similar place to `Trend` and `Rank_Stat` although these two fields are useless.

**Comment by DevilXD** [comment]
This has been implemented in https://github.com/DevilXD/aRez/commit/58e903a4b50cfb9412760a570b932142369bdd05

Please install the latest dev version to see if that's what you've wanted: `pip install --force-reinstall --no-deps git+https://DevilXD/aRez@dev`

**Comment by EthanHicks1** [comment]
A few notes. Not sure if it's just my machine but I had to use the full Github URL with pip in the install command: `pip install --force-reinstall --no-deps git+https://github.com/DevilXD/aRez@dev`

It appears to work as excepted when accessing the ranked data for a player who has finished their placements.  However, it appears that if a player is currently still in their `Qualifying` matches trying to access the field `.postion` will result in an `AttributeError`.

**Comment by DevilXD** [comment]
There's no way an `AttributeError` can be happening there, as the attribute is always present on `RankedStats` objects now, and it not being set would mean the `RankedStats` object wouldn't even be constructed properly.
Are you sure it's not caused by your user code?

**Comment by EthanHicks1** [comment]
Looking again I had something messed up in my code. This issue can be closed as the requested feature has been implemented in dev.
