### ISSUE TITLE
`search_players` in aRez 0.2.5.dev0 results in an AttributeError

### ISSUE THREAD

**Issue by EthanHicks1** [DevilXD/HiRezAPI#5]
Using the function `search_players`  for any name where the default parameter of `exact=true`, will result in an AttributeError.

For example:

`players = await self.bot.api.search_players(player_name=player_name, platform=platform)`

where `playername = yaniv` and `platform = none`.

results in:
```
File "/usr/local/lib/python3.8/dist-packages/arez/api.py", line 703, in search_players
    if exact and name.lower() != player_name:
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by DevilXD** [comment]
Thank you for the report. This should be now fixed via https://github.com/DevilXD/aRez/commit/d629b14fa444bfc0743e4b6ca3a90209e87fbb5b, please try out the latest dev branch.
